mysite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(
        template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index')
]

mysite/pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),

]

mysite/common/models.py
from django.db import models

# Create your models here.

mysite/pybo/models.py
from django.db import models

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    #외래키의 제약 조건을 무시하고 삭제됨
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return str(self.question)

mysite/common/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields =('username', 'email')

mysite/pybo/forms.py
from django import forms
from .models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject' : '제목',
            'content' : '내용'
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = [ 'content' ]
        labels = {
            'content' : '내용'
        }

mysite/common/views.py
from django.shortcuts import render
from .forms import UserForm
from django.contrib.auth import authenticate, login

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password1 = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password1)
            login(request, user)
            return redirect('index')

    else:
        form = UserForm()

    context = {'form': form}
    return  render(request, 'common/signup.html', context)

mysite/pybo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Question, Answer
from django.utils import timezone
from .forms import QuestionForm,AnswerForm

def index(request):
    question_list = Question.objects.order_by('create_date')
    context = {'question_list': question_list}
    return render(request, 'pybo/question_list.html',context)

def detail(request, question_id):
    #question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, id=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html',context)

def answer_create(request, question_id):
    question =get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.question = question
            answer.create_date = timezone.now()
            answer.save()
            return redirect('pybo:detail', question_id=question_id)

    else:
        form = AnswerForm()
    context = {'question':question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)

def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()

    context = {'form' : form }
    return render(request, 'pybo/question_form.html', context)

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, unutual-scale=1">
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Hello~Pybo</title>
</head>
<body>
{% include 'navbar.html' %}
<!--기본 탬플릿 안에 삽입될 내용 start-->
{% block content %}


{% endblock %}
<!--기본 탬플릿 안에 삽입될 내용 end-->
<script src="{% static 'jquery-3.6.0.js' %}"></script>
<script src="{% static 'bootstrap.js' %}"></script>


</body>
</html>

mysite/templates/common/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
  <div class="row">
    <div class="col-4">
      <h4>로그인</h4>
    </div>
    <div class="col-8 text-right">
      <span>또는 <a href="#"> 계정을 만드세요</a></span>
    </div>
  </div>
  <form action="{% url 'common:login' %}" method="post" class="post=form">
    {% csrf_token %}
    {% include 'form_errors.html' %}
<!--아이디-->
    <div class="form-group">
      <label for="username">사용자 ID</label>
      <input type="text" class="form-control" name="username" id="username"
             value="{{ form.username.value|default_if_none:''}}">
    </div>
<!--비밀번호-->
    <div class="form-group">
      <label for="password">비밀번호</label>
      <input type="password" class="form-control" name="password" id="password"
             value="{{ form.password.value|default_if_none:''}}">
    </div>
    <button type="submit" class="btn btn-primary">로그인</button>
  </form>
</div>


{% endblock %}

mysite/templates/form_errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        <strong>{{ field.label }}</strong>
        {{ error }}
      </div>
    {% endfor %}
  {% endfor %}
{% endif %}

mysite/templates/navbar.html
<!--내비게이션바-->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
    <botton class="navbar-toggler ml-auto" type="button" data-toggle="collapse"
       data-target="#navbarNav" aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navar-toggler-icon"></span>
    </botton>
<!--로그인, 로그아웃-->
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{user.username}}(로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

mysite/templates/pybo/question_detail.html
{% load static %}
<link rel="stylesheet" href="{% static 'bootstrap.css' %}">
<div class="container my-3">
  <h2 class="border-bottom py-2">{{ question.subject }}</h2>
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text" style="white-space: pre-line">
        {{ question.content }}
      </div>
      <div class="d-flex justify-content-end">
        <div class="badge badge-light p-2">
          {{ question.create_date }}
        </div>
      </div>
    </div>
  </div>
  <h5 class="border-bottom my-3 py-2">
    {{ question.answer_set.conut }}개의 답변이 있습니다.
  </h5>
  {% for answer in question.answer_set.all %}
    <div class="card-body">
      <div class="card-text" style="white-space: pre-line">
        {{ answer.content }}
      </div>
      <div class="d-flex justify-content-end">
        <div class="badge badge-light p-2">
          {{ answer.create_date }}
        </div>
      </div>
    </div>
  {% endfor %}
<form action="{% url 'pybo:answer_create' question.id %}" method="post">
  {% csrf_token %}
      <div class="alert alert-danger" role="alert">
      {% for field in form %}
        {% if field.errors %}
          <strong>{{ field.label }}</strong>
            {{ field.errors }}
        {% endif %}
      {% endfor %}
    </div>
  <div class="form-group">
    <textarea name="content" id="content" rows="10" class="form-control"></textarea>
  </div>
  <input type="submit" value="답변 등록" class="btn-primary">
</form>
</div>

mysite/templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <h5 class="my-3 border-bottom pb-2">질문 등록</h5>
  <form method="post" class="post-form my-3">
    {% csrf_token %}
    {% if form.errors %}
      <div class="alert alert-danger" role="alert">
        {% for field in form %}
          {% if field.errors %}
            <strong>{{ field.label }}</strong>
              {{ field.errors }}
          {% endif %}
        {% endfor %}
      </div>
    {% endif %}
      <div class="form-group">
        <label for="subject">제목</label>
        <input type="text" name="subject" id="subject" class="form-control"
               value="{{form.subject.value|default_if_none:''}}">
      </div>
      <div class="form-group">
        <label for="content">내용</label>
        <textarea name="content" id="content" class="form-control"
                  rows="10">{{ form.content.value|default_if_none:'' }}</textarea>

      </div>
      <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>
{% endblock %}

mysite/templates/pybo/question_list.html
{% extends 'base.html' %} <!--탬플릿 상속-->
{% block content %}
<div class="container-my-3">
  <table class="table">
    <thead>
      <tr class="thead-dark">
        <th>번호</th>
        <th>제목</th>
        <th>일자</th>
      </tr>
    </thead>
    <tbody>
        {% if question_list %}
            {% for question in question_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a></td>
                <td>{{ question.create_date }}</td>
            </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">질문이 없습니다.</td>
            </tr>
        {% endif %}
    </tbody>
  </table>
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}